name: Terraform Workflow

on:
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - README.md
  workflow_run:
    workflows: [Build and deploy container app to Azure Web App - ruby-github-actions]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Plan for prod
        run: terraform plan
      - name: Terraform Apply for prod
        env:
          TF_VAR_docker_registry: https://aseaudi.azurecr.io/
          TF_VAR_docker_username: ${{ secrets.AzureAppService_ContainerUsername_3b48a09588d34b2aa06c18b651dee1be }}
          TF_VAR_docker_password: ${{ secrets.AzureAppService_ContainerPassword_41be41b1df284be6ad4a33b172205d85 }}
          TF_VAR_docker_image: 'aseaudi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3b48a09588d34b2aa06c18b651dee1be }}/ruby-dev:${{ github.sha }}'
        run: terraform apply --auto-approve