name: Terraform Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Terraform Plan for prod
        run: terraform plan
      - name: Terraform Apply for prod
        run: terraform apply --auto-approve