name: Terraform Workflow

on:
  push:
    branches:
      - development
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"
      - name: Terraform Init
        run: |
          terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCESS_KEY }}" -no-color
      - name: Run Custom Validation Script
        run: |
          ./ListWorkspace.ps1 -CommaSeparatedListofWorkspaces "default, Dev, QA, prod"
        shell: pwsh

  prod-plan:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: 9c6ea0cb-02d3-4113-b1ac-206a139fdda6
          tenant-id: 5a6bd267-db99-42f9-9969-8c87f91cbc21
          subscription-id: c36672c6-f5ca-485e-8785-c76c3e6a1c35
      - name: Terraform Plan for prod
        run: |
          terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCESS_KEY }}" -no-color
          terraform workspace select prod -no-color
          terraform plan -var access_key="${{ secrets.STORAGE_ACCESS_KEY }}" -var tenant_id="${{ secrets.AZURE_TENANT_ID }}" -var-file="prod/prod.tfvars" -no-color

  prod-apply:
    needs: prod-plan
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"
      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: |
                {
                "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
                "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
                }
      - name: Terraform Apply for prod
        run: |
          terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCESS_KEY }}" -no-color
          terraform workspace select prod -no-color
          terraform apply -var access_key="${{ secrets.STORAGE_ACCESS_KEY }}" -var tenant_id="${{ secrets.AZURE_TENANT_ID }}" -var-file="prod/prod.tfvars" --auto-approve -no-color
