name: Terraform Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.7"
      - name: Terraform Init
        run: terraform init
  #       run: |
  #         terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCESS_KEY }}" -no-color
  #     - name: Run Custom Validation Script
  #       run: |
  #         ./ListWorkspace.ps1 -CommaSeparatedListofWorkspaces "default, Dev, QA, prod"
  #       shell: pwsh

  # prod-plan:
  #   needs: validate
  #   runs-on: ubuntu-latest
  #   steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: "1.5.7"
      - name: Login to Azure
        uses: azure/login@v1
        with:
            # creds: |
            #     {
            #     "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            #     "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            #     "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            #     "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            #     }
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     # - name: Terraform Plan for prod
  #     #   run: |
  #     #     terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCESS_KEY }}" -no-color
  #     #     terraform workspace select prod -no-color
  #     #     terraform plan -var access_key="${{ secrets.STORAGE_ACCESS_KEY }}" -var tenant_id="${{ secrets.AZURE_TENANT_ID }}" -var-file="prod/prod.tfvars" -no-color
      - name: Terraform Plan for prod
        run: terraform plan

  # prod-apply:
  #   needs: prod-plan
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: prod
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_version: "1.5.7"
  #     - name: Login to Azure
  #       uses: azure/login@v1
  #       with:
  #           creds: |
  #               {
  #               "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
  #               "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
  #               "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
  #               "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  #               }
      # - name: Terraform Apply for prod
      #   run: |
      #     terraform init -backend-config="access_key=${{ secrets.STORAGE_ACCESS_KEY }}" -no-color
      #     terraform workspace select prod -no-color
      #     terraform apply -var access_key="${{ secrets.STORAGE_ACCESS_KEY }}" -var tenant_id="${{ secrets.AZURE_TENANT_ID }}" -var-file="prod/prod.tfvars" --auto-approve -no-color
      - name: Terraform Apply for prod
        run: terraform apply