# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build container app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://aseaudi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3b48a09588d34b2aa06c18b651dee1be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_41be41b1df284be6ad4a33b172205d85 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: aseaudi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3b48a09588d34b2aa06c18b651dee1be }}/ruby-dev:${{ github.sha }}
        file: ./Dockerfile
